# Generated by Django 5.1.2 on 2024-10-22 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('ktpname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed', regex='^[a-zA-Z\\s]+$')])),
                ('firstname', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed', regex='^[a-zA-Z\\s]+$')])),
                ('middlename', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed', regex='^[a-zA-Z\\s]+$')])),
                ('lastname', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed', regex='^[a-zA-Z\\s]+$')])),
                ('memberstatus', models.IntegerField()),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
